version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=GameDevForumDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5438:5432'