spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/GameDevForumDB
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog-master.yml
  security:
    user:
      password: admin
      name: admin
jwt:
  expiration-seconds: 60000