spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/GameDevForumDB
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog-master.yml
  security:
    user:
      password: admin
      name: admin